version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--api.insecure=true" # enables the Traefik API. True by default
      - "--providers.docker=true" # enables the Docker provider
      - "--providers.docker.exposedbydefault=false" # prevents Traefik from creating routes for containers that don't have a traefik.enable=true label
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=<YOUR_EMAIL_ADDRESS>"# Email address used for registration
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "443:443" # sets the port for HTTP
      - "8080:8080" # sets the port for HTTPS
    volumes:
      - "./letsencrypt:/letsencrypt" # Copies the Let's Encrypt certificate locally for ease of backing up
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - backend
